import fs from 'node:fs';
import path from 'node:path';
import {company} from '../data/company.js';
import {categories,services} from '../data/catalog.js';
import {projects} from '../data/projects.js';
import {news} from '../data/news.js';
import {base,origin,esc,url,pic,button,header,footer,crumbs,heading,sectionHead,cta,categoryCards,projectGrid,projectCard,gallery,steps} from '../src/components.js';
const out='dist'; fs.mkdirSync(out,{recursive:true});
fs.cpSync('assets',out+'/assets',{recursive:true});
fs.copyFileSync('src/styles.css',out+'/assets/styles.css'); fs.copyFileSync('src/app.js',out+'/assets/app.js');
const routes=[];
const list=items=>`<ul class="plain-list">${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`;
const section=(content,cls='')=>`<section class="wrap section ${cls}">${content}</section>`;
const serviceLink=s=>`catalog/${s.category}/${s.id}/`;
function page(route,title,description,content,active='',cover=148){
 const canonical=origin+url(route); routes.push(route);
 const schema={'@context':'https://schema.org','@type':'Organization',name:'РПК «Технология»',url:origin+base,telephone:company.phoneHref,email:company.email,address:{'@type':'PostalAddress',streetAddress:'ул. Мира, 3п, стр. 1',addressLocality:'Нижневартовск',addressCountry:'RU'},sameAs:[company.vk,company.map]};
 const html=`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — Технология, Нижневартовск</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:title" content="${esc(title)} — Технология"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin+url(`assets/images/work-${String(cover).padStart(3,'0')}.webp`)}"><link rel="icon" type="image/png" href="${url('assets/images/logo.png')}"><link rel="stylesheet" href="${url('assets/styles.css')}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script src="${url('assets/app.js')}" defer></script></head><body>${header(active)}<main id="main">${content}</main>${footer()}</body></html>`;
 const dest=path.join(out,route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);
}
page('','Рекламное производство для бизнеса и города','Вывески, печать, конструкции и оформление мероприятий. Реальные работы РПК «Технология» в Нижневартовске. Каталог и запрос расчёта.',`
<section class="wrap hero"><div class="hero-copy"><span class="eyebrow">Рекламно-производственная компания</span><h1>Рекламное <br>производство. <br>Для бизнеса <br>и города.</h1><p class="lead">Вывески, печать, конструкции и оформление мероприятий в Нижневартовске.</p><div class="actions">${button('Смотреть каталог','catalog/')}${button('Запросить расчёт','contacts/#request',true)}</div><span class="hero-region">Работаем по ХМАО и ЯНАО</span></div><figure class="hero-photo">${pic(148,'Арка «Дружба народов» на фестивале «Самотлорские ночи»',{hero:true})}<figcaption><span>Самотлорские ночи · 2026</span><a href="${url('portfolio/samotlor-nights/')}">Смотреть проект ↗</a></figcaption></figure></section>
${section(sectionHead('Каталог','От вывески до оформления события','catalog/','Все направления')+categoryCards())}
${section(sectionHead('Сделано в «Технологии»','Работы, которые вы видели','portfolio/','Всё портфолио')+projectGrid(['ohotaktiv','rosneft','green-land','yadro','literary-square','samotlor-sport']))}
${section(`<div class="feature-split"><figure>${pic(209,'Объёмная спортивная композиция у СШОР «Самотлор»')}<figcaption>Объёмные элементы · СШОР «Самотлор»</figcaption></figure><div><span class="eyebrow">Производственные возможности</span><h2>Изображение.<br>Материал.<br>Готовый объект.</h2><p>Печать, резка неметаллов, гравировка и изготовление рекламных конструкций. Подбираем исполнение под место, масштаб и назначение изделия.</p>${button('О производстве','production/',true)}</div></div>`)}
${section(sectionHead('Как заказать','Начнём с вашей задачи')+steps())}${cta()}`);
page('catalog/','Каталог рекламной продукции и услуг','Шесть направлений: вывески, печать и текстиль, полиграфия, сувениры, резка и оформление мероприятий.',crumbs([['Каталог']])+heading('Шесть направлений','Что нужно изготовить?','Выберите направление, изучите варианты и реальные работы. Для расчёта расскажите о своей задаче.')+section(categoryCards(),'catalog-section')+section(sectionHead('Подробно об изделиях','От задачи к конкретному решению')+`<div class="service-grid">${services.map(s=>`<a class="service-card" href="${url(serviceLink(s))}">${pic(s.images[0],s.title,{small:true})}<h3>${s.title} ↗</h3><p>${s.lead}</p></a>`).join('')}</div>`)+cta(),'catalog/');
for(const c of categories){
 const detail=`<div class="detail-list">${c.details.map(([t,p],i)=>{const s=services.find(s=>s.category===c.id&&(s.title===t||(t==='Баннеры'&&s.id==='banners')||(t==='Флаги'&&s.id==='flags')));return `<article><span class="step-number">0${i+1}</span><div><h2>${t}</h2><p>${p}</p></div>${s?button('Подробнее',serviceLink(s),true):button('Обсудить задачу','contacts/?service='+encodeURIComponent(t)+'#request',true)}</article>`}).join('')}</div>`;
 page('catalog/'+c.id+'/',c.title,c.description,crumbs([['Каталог','catalog/'],[c.title]])+heading('Каталог / '+String(categories.indexOf(c)+1).padStart(2,'0'),c.title,c.description)+section(detail)+(c.projects.length?section(sectionHead('Реальные работы',c.intro)+projectGrid(c.projects)):'')+cta(c.title),'catalog/',c.image||148);
}
for(const s of services){const c=categories.find(c=>c.id===s.category);page(serviceLink(s),s.title,s.description,crumbs([['Каталог','catalog/'],[c.title,'catalog/'+c.id+'/'],[s.title]])+heading(c.title,s.title,s.lead)+section(`<div class="feature-split service-intro"><figure>${pic(s.images[0],s.alts[0],{hero:true})}</figure><div><p class="lead">${s.description}</p>${button('Запросить расчёт','contacts/?service='+encodeURIComponent(s.title)+'#request')}<p class="minor">Стоимость и сроки — после уточнения параметров.</p></div></div>`)+section(`<div class="info-columns"><div><h2>Для каких задач</h2>${list(s.tasks)}</div><div><h2>Варианты исполнения</h2>${list(s.variants)}</div><div><h2>Что нужно для расчёта</h2>${list(s.parameters)}</div></div><p class="note">${s.note}</p>`)+section(sectionHead('Детали и ракурсы','Как это выглядит')+gallery(s.images,s.alts))+section(sectionHead('В портфолио','Проекты с этим решением')+projectGrid(s.projects))+cta(s.title),'catalog/',s.images[0]);}
page('portfolio/','Портфолио: вывески и оформление','12 реальных работ «Технологии»: вывески, городские объекты, баннеры, оформление мероприятий и фотозоны.',crumbs([['Портфолио']])+heading('Реальные объекты','Сделано в «Технологии»','Для магазинов, городских пространств и событий. Выберите направление или откройте фотографии проекта.')+section(`<div class="filters" role="group" aria-label="Фильтр проектов">${['Все',...new Set(projects.map(p=>p.tag))].map((t,i)=>`<button type="button" data-filter="${t}" aria-pressed="${i===0}">${t}</button>`).join('')}</div><p class="filter-count minor" aria-live="polite">Показано проектов: ${projects.length}</p><div class="project-grid">${projects.map(projectCard).join('')}</div><p class="empty-state" hidden>В этом направлении пока нет фотографий. Посмотрите все проекты.</p>`)+cta(),'portfolio/');
for(const p of projects.filter(p=>p.page))page('portfolio/'+p.id+'/',p.title,p.description,crumbs([['Портфолио','portfolio/'],[p.title]])+heading(p.tag+(p.year?' · '+p.year:''),p.title,p.caption)+section(`<figure class="case-hero">${pic(p.cover,p.caption,{hero:true})}</figure><div class="case-story"><h2>О проекте</h2><div><p class="lead">${p.description}</p><h3>В деталях</h3>${list(p.facts)}</div></div>`)+section(sectionHead('Фотообзор','Общий вид и детали')+gallery(p.images,null,p.title))+section(sectionHead('Каталог','Связанные услуги')+`<div class="actions">${p.services.map(id=>services.find(s=>s.id===id)).map(s=>button(s.title,serviceLink(s),true)).join('')}</div>`)+cta('Проект, похожий на «'+p.title+'»'),'portfolio/',p.cover);
page('production/','Производственные возможности','Широкоформатная, УФ- и DTF-печать, лазерная резка и фрезеровка неметаллов, гравировка и рекламные конструкции.',crumbs([['Производство']])+heading('От макета до изделия','Возможности производства','Печатная графика, обработка материалов и объёмные решения. Технология выбирается под задачу и условия использования.')+section(`<div class="feature-split"><figure>${pic(87,'Вечерний вид входной арки Парка Победы',{hero:true})}<figcaption>Результат производства: входная арка Парка Победы</figcaption></figure><div><h2>Разный масштаб.<br>Один подход.</h2><p>Сначала определяем назначение изделия, размеры и место размещения. Затем согласуем материалы, технологию и детали исполнения.</p><p>Посмотрите готовые работы и обсудите технические требования со специалистом.</p>${button('Смотреть работы','portfolio/',true)}</div></div>`)+section(`<div class="capability-grid">${[['Широкоформатная печать','Баннеры и крупная графика для фасадов, конструкций и мероприятий.','printing'],['УФ-печать','Нанесение изображения с учётом свойств материала и поверхности.','printing'],['DTF-печать','Перенос изображений на текстиль для индивидуальных и корпоративных задач.','printing'],['Лазерная резка','Контурные детали из неметаллических материалов по согласованному макету.','fabrication'],['Фрезеровка и гравировка','Обработка неметаллов, надписи и графика на изделиях.','fabrication'],['Рекламные конструкции','Вывески, объёмные элементы и оформление пространств.','signage']].map(([t,p,c])=>`<article><h2>${t}</h2><p>${p}</p><a class="text-link" href="${url('catalog/'+c+'/')}">В каталог ↗</a></article>`).join('')}</div>`)+section(sectionHead('Рабочий процесс','Начинаем с исходных данных')+steps())+cta(),'production/',87);
page('about/','О рекламно-производственной компании','«Технология» в Нижневартовске: рекламная, печатная и оформительская продукция. Адрес: Мира, 3п, стр. 1. Работа по ХМАО и ЯНАО.',crumbs([['О компании']])+heading('Нижневартовск · ХМАО и ЯНАО','Технология вашего проекта','Рекламно-производственная компания. Изготавливаем вывески, печатную продукцию и элементы оформления для бизнеса, организаций и событий.')+section(`<div class="feature-split"><figure>${pic(244,'Здание компании «Технология»',{hero:true})}<figcaption>Нижневартовск, ул. Мира, 3п, стр. 1</figcaption></figure><div><h2>От вывески магазина<br>до городского праздника</h2><p>В портфолио — вывески Green Land и «ОхотАктив», оформление «Самотлорских ночей», объекты у городской библиотеки и СШОР «Самотлор».</p><p>Каталог объединяет основные направления. Примеры помогают выбрать решение, а специалисты — уточнить исполнение под ваш объект.</p><div class="actions">${button('Каталог','catalog/')}${button('Наши работы','portfolio/',true)}</div></div></div>`)+section(sectionHead('Подход к работе','Сначала задача. Затем технология.')+steps())+cta(),'about/',244);
page('news/','Проекты и новости компании','Фотообзоры выполненных работ: «Самотлорские ночи», оформление ко Дню нефтяника и вывески «ОхотАктив».',crumbs([['Проекты и новости']])+heading('Из жизни проектов','Новые ракурсы знакомых работ','Фотообзоры оформления, вывесок и городских объектов из портфолио компании.')+section(`<div class="news-list">${news.map(n=>`<article><a href="${url('portfolio/'+n.project+'/')}">${pic(n.image,n.title,{small:true})}</a><div><span class="eyebrow">${n.label}</span><h2><a href="${url('portfolio/'+n.project+'/')}">${n.title}</a></h2><p>${n.text}</p><a class="text-link" href="${url('portfolio/'+n.project+'/')}">Смотреть фотообзор ↗</a></div></article>`).join('')}</div>`)+cta(),'news/');
page('contacts/','Контакты и запрос расчёта','Связаться с «Технологией»: '+company.phone+', '+company.email+'. Нижневартовск, Мира, 3п, стр. 1. MAX, VK и запрос расчёта.',crumbs([['Контакты']])+heading('На связи','Обсудим вашу задачу','Позвоните, напишите в MAX или подготовьте письмо с описанием изделия.')+section(`<div class="contact-grid"><div><span class="eyebrow">Телефон</span><a class="contact-large" href="tel:${company.phoneHref}">${company.phone}</a><a href="tel:${company.mobileHref}">${company.mobile}</a><span class="eyebrow">Электронная почта</span><a class="contact-large" href="mailto:${company.email}">${company.email}</a><div class="actions"><a class="button" href="${company.max}" target="_blank" rel="noopener">Написать в MAX ↗</a><a class="button button-outline" href="${company.vk}" target="_blank" rel="noopener">ВКонтакте ↗</a></div></div><div><span class="eyebrow">Приехать к нам</span><h2>${company.address}</h2><p>Перед визитом уточните время работы по телефону. Актуальный график — в карточке компании.</p><a class="text-link" href="${company.map}" target="_blank" rel="noopener">Маршрут и часы работы в 2ГИС ↗</a></div></div>`)+section(`<div class="request-layout" id="request"><div><span class="eyebrow">Запрос расчёта</span><h2>Расскажите,<br>что задумали.</h2><p>Укажите размеры, количество и место использования. Макет или фотографии можно приложить к письму в вашей почтовой программе.</p><p class="minor">Форма подготовит письмо на ${company.email}. Отправку вы подтвердите в почтовой программе. Данные не сохраняются на сайте.</p></div><form id="request-form" data-email="${company.email}"><div class="form-row"><label>Ваше имя<input name="name" autocomplete="name" maxlength="100" required></label><label>Телефон или способ связи<input name="contact" autocomplete="tel" maxlength="150" required></label></div><label>Что нужно изготовить<input name="service" maxlength="180" placeholder="Например, световую вывеску" required></label><label>Комментарий<textarea name="comment" rows="4" maxlength="1800" placeholder="Размеры, количество, город и другие детали"></textarea></label><button class="button" type="submit">Запросить расчёт ↗</button><p class="minor">Откроется почтовая программа с подготовленным письмом.</p><p id="form-status" role="status"></p><a id="mail-fallback" hidden>Открыть письмо ещё раз ↗</a></form></div>`),'contacts/');
fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${origin+url(r)}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(out+'/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin+base}sitemap.xml\n`);
fs.writeFileSync(out+'/.nojekyll','');
fs.writeFileSync(out+'/404.html',`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex"><title>Страница не найдена — Технология</title><link rel="stylesheet" href="${url('assets/styles.css')}"><main class="wrap page-heading"><span class="eyebrow">Ошибка 404</span><h1>Страница не найдена</h1><p>Перейдите в каталог или вернитесь на главную.</p>${button('Открыть каталог','catalog/')}</main></html>`);
fs.writeFileSync('data/routes.json',JSON.stringify(routes,null,2));console.log(`Built ${routes.length} pages → dist`);
