const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-navigation');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open');menu.focus()}});
const dialog=document.querySelector('.lightbox');let photos=[],position=0,opener;
function showPhoto(){const p=photos[position];if(!p)return;const img=dialog.querySelector('img');img.src=p.src;img.alt=p.alt;dialog.querySelector('figcaption').textContent=`${position+1} / ${photos.length} · ${p.alt}`;dialog.querySelector('.lightbox-prev').hidden=dialog.querySelector('.lightbox-next').hidden=photos.length<2}
document.querySelectorAll('[data-gallery]').forEach(el=>el.addEventListener('click',()=>{photos=JSON.parse(el.dataset.gallery);position=Number(el.dataset.index||0);opener=el;showPhoto();dialog.showModal()}));
dialog?.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());
dialog?.querySelector('.lightbox-prev').addEventListener('click',()=>{position=(position-1+photos.length)%photos.length;showPhoto()});
dialog?.querySelector('.lightbox-next').addEventListener('click',()=>{position=(position+1)%photos.length;showPhoto()});
dialog?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();position=(position+(e.key==='ArrowRight'?1:-1)+photos.length)%photos.length;showPhoto()}});
dialog?.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
dialog?.addEventListener('close',()=>opener?.focus());
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('[data-tag]').forEach(card=>{card.hidden=button.dataset.filter!=='Все'&&card.dataset.tag!==button.dataset.filter;if(!card.hidden)count++});document.querySelector('.filter-count').textContent=`Показано проектов: ${count}`;document.querySelector('.empty-state').hidden=count>0}));
const form=document.querySelector('#request-form');
if(form){form.elements.service.value=new URLSearchParams(location.search).get('service')?.slice(0,180)||'';form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form),body=`Имя: ${data.get('name')}\nСвязь: ${data.get('contact')}\nИзделие: ${data.get('service')}\n\n${data.get('comment')}`;const href=`mailto:${form.dataset.email}?subject=${encodeURIComponent('Запрос расчёта: '+data.get('service'))}&body=${encodeURIComponent(body)}`;const fallback=document.querySelector('#mail-fallback');fallback.href=href;fallback.hidden=false;document.querySelector('#form-status').textContent='Письмо подготовлено. Подтвердите отправку в почтовой программе. Если она не открылась, напишите нам в MAX или позвоните.';location.href=href})}
