import {company} from '../data/company.js';
import {categories} from '../data/catalog.js';
import {projects} from '../data/projects.js';
import {news} from '../data/news.js';
import fs from 'node:fs';
const media=JSON.parse(fs.readFileSync(new URL('../data/media.json',import.meta.url),'utf8'));
export const base='/tehnologiya-nizhnevartovsk/';
export const origin='https://evsavelev.github.io';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const url=p=>base+p;
export const imagePath=(n,small=false)=>`assets/images/work-${String(n).padStart(3,'0')}${small?'-sm':''}.webp`;
export function pic(n,alt,{hero=false,cls='',small=false}={}) {const m=media.find(m=>m.file===imagePath(n));if(!m)throw new Error('Missing media '+n);return `<img class="${cls}" src="${url(imagePath(n,small))}" srcset="${url(imagePath(n,true))} ${m.smallWidth}w, ${url(imagePath(n))} ${m.width}w" sizes="${hero?'(max-width: 760px) calc(100vw - 40px), 55vw':small?'(max-width: 760px) calc(100vw - 40px), (max-width: 900px) 45vw, 30vw':'(max-width: 760px) calc(100vw - 40px), 50vw'}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
export const arrow='<span aria-hidden="true">↗</span>';
export function button(text,path,secondary=false){return `<a class="button${secondary?' button-outline':''}" href="${url(path)}">${text}${arrow}</a>`;}
export function header(active){const nav=[['','Главная'],['catalog/','Каталог'],['portfolio/','Портфолио'],['production/','Производство'],['about/','О компании'],['news/','Проекты и новости'],['contacts/','Контакты']];return `<a class="skip-link" href="#main">Перейти к содержимому</a><div class="utility"><div class="wrap utility-inner"><span>Нижневартовск · ХМАО и ЯНАО</span><a href="${company.map}" target="_blank" rel="noopener">Мира, 3п, стр. 1 ${arrow}</a></div></div><header class="site-header"><div class="wrap header-main"><a class="brand" href="${url('')}" aria-label="Технология — главная"><img src="${url('assets/images/logo.png')}" width="2713" height="686" alt="Технология. Рекламно-производственная компания"></a><div class="header-contact"><a class="phone" href="tel:${company.phoneHref}">${company.phone}</a><a class="minor" href="${company.max}" target="_blank" rel="noopener">Написать в MAX ${arrow}</a></div>${button('Запросить расчёт','contacts/#request')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-navigation"><span>Меню</span><span class="menu-symbol" aria-hidden="true">☰</span></button></div><nav class="wrap navigation" id="main-navigation" aria-label="Основная навигация">${nav.map(([p,t])=>`<a href="${url(p)}"${active===p?' aria-current="page"':''}>${t}${p==='catalog/'?'<span aria-hidden="true">↘</span>':''}</a>`).join('')}<a class="mobile-call" href="tel:${company.phoneHref}">${company.phone}</a></nav></header>`;}
export function footer(){return `<footer class="site-footer"><div class="wrap footer-grid"><div><a class="footer-wordmark" href="${url('')}">Технология</a><p>Рекламное производство.<br>От идеи до готового объекта.</p><span class="minor">Нижневартовск · ХМАО и ЯНАО</span></div><div><span class="eyebrow">Разделы</span><a href="${url('catalog/')}">Каталог</a><a href="${url('portfolio/')}">Портфолио</a><a href="${url('production/')}">Производство</a><a href="${url('about/')}">О компании</a><a href="${url('news/')}">Проекты и новости</a></div><div><span class="eyebrow">Связаться</span><a href="tel:${company.phoneHref}">${company.phone}</a><a href="mailto:${company.email}">${company.email}</a><a href="${company.max}" target="_blank" rel="noopener">MAX ${arrow}</a><a href="${company.vk}" target="_blank" rel="noopener">ВКонтакте ${arrow}</a><a href="${url('contacts/')}">Контакты и адрес ${arrow}</a></div></div><div class="wrap footer-bottom"><span>© 2026 РПК «Технология»</span><span>Мира, 3п, стр. 1</span><span>Демонстрационная версия сайта</span></div></footer><dialog class="lightbox" aria-label="Просмотр фотографий"><button class="lightbox-close" type="button" aria-label="Закрыть галерею">Закрыть ×</button><button class="lightbox-prev" type="button" aria-label="Предыдущее фото">←</button><figure><img alt="" width="1800" height="1200"><figcaption aria-live="polite"></figcaption></figure><button class="lightbox-next" type="button" aria-label="Следующее фото">→</button></dialog>`;}
export function crumbs(items){return `<nav class="breadcrumbs wrap" aria-label="Хлебные крошки"><a href="${url('')}">Главная</a>${items.map(([t,p])=>`<span aria-hidden="true">/</span>${p?`<a href="${url(p)}">${esc(t)}</a>`:`<span aria-current="page">${esc(t)}</span>`}`).join('')}</nav>`;}
export function heading(kicker,title,description){return `<section class="wrap page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1>${description?`<p class="lead">${description}</p>`:''}</section>`;}
export function sectionHead(kicker,title,link,label){return `<div class="section-heading"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div>${link?`<a class="text-link" href="${url(link)}">${label||'Подробнее'} ${arrow}</a>`:''}</div>`;}
export function cta(subject=''){return `<section class="wrap cta-section"><div><span class="eyebrow">Обсудим вашу задачу</span><h2>Что нужно<br>изготовить?</h2></div><div><p>Расскажите об идее, размерах и количестве. Специалисты уточнят детали и подготовят расчёт.</p>${button('Запросить расчёт',`contacts/${subject?'?service='+encodeURIComponent(subject):''}#request`)}<a class="cta-phone" href="tel:${company.phoneHref}">${company.phone}</a></div></section>`;}
export function categoryCards(){return `<div class="category-grid">${categories.map((c,i)=>`<a class="category-card" href="${url('catalog/'+c.id+'/')}"><span class="category-number">0${i+1}</span><div><h3>${c.title}</h3><p>${c.items.slice(0,3).join(' · ')}</p></div>${arrow}</a>`).join('')}</div>`;}
export function projectCard(p){const gallery=JSON.stringify(p.images.map(n=>({src:url(imagePath(n)),alt:p.title+' — '+p.caption})));return `<article class="project-card" data-tag="${esc(p.tag)}"><${p.page?'a':'button'} ${p.page?`href="${url('portfolio/'+p.id+'/')}"`:`type="button" data-gallery='${esc(gallery)}'`} class="project-media" aria-label="${esc(p.page?'Открыть проект '+p.title:'Смотреть фотографии: '+p.title)}">${pic(p.cover,p.title+' — '+p.caption,{small:true})}<span class="image-action" aria-hidden="true">${p.page?'Смотреть проект ↗':'Смотреть фото ＋'}</span></${p.page?'a':'button'}><div class="project-meta"><span>${p.tag}</span>${p.year?`<span>${p.year}</span>`:''}</div><h3>${p.page?`<a href="${url('portfolio/'+p.id+'/')}">${p.title}</a>`:p.title}</h3><p>${p.caption}</p><a class="project-category-link text-link" href="${url('catalog/'+p.category+'/')}">Услуги этого направления ↗</a></article>`;}
export function projectGrid(ids){return `<div class="project-grid">${ids.map(id=>projects.find(p=>p.id===id)).filter(Boolean).map(projectCard).join('')}</div>`;}
export function gallery(images,alts,title='Фотографии проекта'){const photos=images.map((n,i)=>({src:url(imagePath(n)),alt:alts?.[i]||title+' — фото '+(i+1)}));return `<div class="gallery-grid">${images.map((n,i)=>`<button type="button" class="gallery-item" data-gallery='${esc(JSON.stringify(photos))}' data-index="${i}" aria-label="Увеличить: ${esc(photos[i].alt)}">${pic(n,photos[i].alt,{small:true})}<span aria-hidden="true">＋</span></button>`).join('')}</div>`;}
export function steps(){return `<div class="steps">${[['Расскажите о задаче','Что хотите получить, где будет использоваться изделие и в каком количестве.'],['Поделитесь исходными данными','Размеры, фотографии места, эскиз или готовый макет, если он есть.'],['Согласуйте решение','Компания уточнит параметры, рассчитает стоимость и обсудит сроки.'],['Перейдите к реализации','Производство и работы выполняются по согласованным условиям.']].map(([t,p],i)=>`<div><span class="step-number">0${i+1}</span><h3>${t}</h3><p>${p}</p></div>`).join('')}</div>`;}
export function quickCatalog(){return `<nav class="wrap quick-catalog" aria-label="Быстрый переход по каталогу">${categories.map((c,i)=>`<a href="${url('catalog/'+c.id+'/')}"><span>0${i+1}</span>${c.title}<span aria-hidden="true">↗</span></a>`).join('')}</nav>`;}
export function categoryNav(current){return `<nav class="category-nav" aria-label="Направления каталога"><span class="eyebrow">Все направления</span>${categories.map((c,i)=>`<a href="${url('catalog/'+c.id+'/')}"${c.id===current?' aria-current="page"':''}><span>0${i+1}</span>${c.title}<span aria-hidden="true">↗</span></a>`).join('')}</nav>`;}
export function newsPic(n,{hero=false}={}){return n.image?pic(n.image,n.alt,{small:!hero,hero}):`<img src="${url(n.imageFile)}" width="${n.width}" height="${n.height}" alt="${esc(n.alt)}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
export function newsCards(items=news){return `<div class="news-grid">${items.map(n=>`<article class="news-card"><a class="news-media ${n.id==='vk-497'?'news-contain':''}" href="${n.vk}" target="_blank" rel="noopener" aria-label="${esc(n.title)} — открыть публикацию VK">${newsPic(n)}${n.id==='vk-491'?'<span class="image-action">Видео в VK ↗</span>':''}</a><div class="project-meta"><span>${n.label}</span>${n.dateLabel?`<span>${n.dateLabel}</span>`:''}</div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><div class="news-links"><a class="text-link" href="${n.vk}" target="_blank" rel="noopener">Смотреть в VK ↗</a>${n.project?`<a class="text-link" href="${url('portfolio/'+n.project+'/')}">Проект на сайте ↗</a>`:`<a class="text-link" href="${url('catalog/'+n.category+'/')}">Услуги по теме ↗</a>`}</div></article>`).join('')}</div>`;}
